Goiztiri/Goiztiri/Models/GoiztiriFContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Goiztiri.Models
{
    public class GoiztiriFContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public GoiztiriFContext() : base("name=GoiztiriFContext")
        {
        }

        public System.Data.Entity.DbSet<GoiztiriWeb.Models.Jugador> Jugadores { get; set; }
    }
}

Goiztiri/Goiztiri/Models/Jugador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GoiztiriWeb.Models
{
    public class Jugador
    {
        public string Ruta { get; set; }
        public int CodEquipo { get; set; }
        [Key]
        public int CodJugador{ get; set; }
        public int Dorsal { get; set; }
        public string Nombre{ get; set; }
        public string Apellido{ get; set; }
        public int Goles { get; set; }
        public int Asistencias { get; set; }
        public string Demarcacion{ get; set; }


    }
}

Goiztiri/Goiztiri/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Goiztiri.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Plantillas()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Goiztiri/Goiztiri/Controllers/JugadoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Goiztiri.Models;
using GoiztiriWeb.Models;

namespace Goiztiri.Controllers
{
    public class JugadoresController : Controller
    {
        private GoiztiriFContext db = new GoiztiriFContext();

        // GET: Jugadores
        public ActionResult Index()
        {
            return View(db.Jugadores.ToList());
        }

        public ActionResult Femenino()
        {
            return View(db.Jugadores.ToList());
        }

        // GET: Jugadores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jugador jugador = db.Jugadores.Find(id);
            if (jugador == null)
            {
                return HttpNotFound();
            }
            return View(jugador);
        }

        // GET: Jugadores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jugadores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodJugador,Ruta,CodEquipo,Dorsal,Nombre,Apellido,Goles,Asistencias,Demarcacion")] Jugador jugador)
        {
            if (ModelState.IsValid)
            {
                db.Jugadores.Add(jugador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(jugador);
        }

        // GET: Jugadores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jugador jugador = db.Jugadores.Find(id);
            if (jugador == null)
            {
                return HttpNotFound();
            }
            return View(jugador);
        }

        // POST: Jugadores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodJugador,Ruta,CodEquipo,Dorsal,Nombre,Apellido,Goles,Asistencias,Demarcacion")] Jugador jugador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jugador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(jugador);
        }

        // GET: Jugadores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jugador jugador = db.Jugadores.Find(id);
            if (jugador == null)
            {
                return HttpNotFound();
            }
            return View(jugador);
        }

        // POST: Jugadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Jugador jugador = db.Jugadores.Find(id);
            db.Jugadores.Remove(jugador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Goiztiri/Goiztiri/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Goiztiri/Goiztiri/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Goiztiri/Goiztiri/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron">
    <div class="text-center">
        <img class="img-fluid mx-auto" width="800" src="~/Content/img/iconos/portada.png" />
    </div>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>Nueva temporada</h2>
        <p>Nueva temporada del Goiztiri Agrupacion Deportiva...Aupa Goiztiri!!!</p>
        <!-- 21:9 aspect ratio -->

        <div class="embed-responsive embed-responsive-16by9">
            <iframe src="https://www.youtube.com/embed/w4RXihk5FwY?ecver=2" style="position:absolute;width:100%;height:100%;left:0" width="641" height="360" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <p><a class="btn btn-default" href="https://www.facebook.com/photo.php?fbid=10216168120893939&set=a.4208431487251&type=3&theater">Leer más &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Cena de Equipo</h2>
        <p>
            No pudo ser,empate a 1 en Bakio,pero después todos juntos de nuevo. Aún queda mucho,mucho por hacer...
       
        </p>
        <img class="img-fluid mx-auto" width="800" src="https://scontent.fbio1-1.fna.fbcdn.net/v/t1.0-9/44961446_10216168121093944_1334629317358911488_n.jpg?_nc_cat=105&_nc_ht=scontent.fbio1-1.fna&oh=8cec3bf2cdc89504bd092d644c3a8cc6&oe=5C4553BC" />
        <p><a class="btn btn-default" href="https://www.facebook.com/photo.php?fbid=10216168120893939&set=a.4208431487251&type=3&theater">Leer más &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Nuestra Cantera</h2>
        <p>Nos ganaron ... Y que!!!...y lo bien que se lo pasan...eso es lo importante!!!... </p>
        <img class="img-fluid mx-auto" width="800" src="https://scontent.fbio1-1.fna.fbcdn.net/v/t1.0-9/44870331_10212695172355981_5742032891458617344_n.jpg?_nc_cat=105&_nc_ht=scontent.fbio1-1.fna&oh=226f7b824bc56362025417994bedda66&oe=5C789BAE" />
        <p><a class="btn btn-default" href="https://www.facebook.com/photo.php?fbid=10216168120893939&set=a.4208431487251&type=3&theater">Leer más &raquo;</a></p>
    </div>
</div>

Goiztiri/Goiztiri/Views/Home/Plantillas.cshtml
@{
    ViewBag.Title = "Plantillas";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Goiztiri/Goiztiri/Views/Jugadores/Create.cshtml
@model GoiztiriWeb.Models.Jugador

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jugador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ruta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ruta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodEquipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodEquipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodEquipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dorsal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dorsal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dorsal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Goles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Goles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Goles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Asistencias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Asistencias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Asistencias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Demarcacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Demarcacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Demarcacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Goiztiri/Goiztiri/Views/Jugadores/Delete.cshtml
@model GoiztiriWeb.Models.Jugador

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jugador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ruta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ruta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodEquipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodEquipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dorsal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dorsal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Asistencias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Asistencias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Demarcacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Demarcacion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Goiztiri/Goiztiri/Views/Jugadores/Details.cshtml
@model GoiztiriWeb.Models.Jugador

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Jugador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ruta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ruta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodEquipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodEquipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dorsal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dorsal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Asistencias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Asistencias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Demarcacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Demarcacion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CodJugador }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Goiztiri/Goiztiri/Views/Jugadores/Edit.cshtml
@model GoiztiriWeb.Models.Jugador

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jugador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CodJugador)

        <div class="form-group">
            @Html.LabelFor(model => model.Ruta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ruta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodEquipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodEquipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodEquipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dorsal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dorsal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dorsal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Goles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Goles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Goles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Asistencias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Asistencias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Asistencias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Demarcacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Demarcacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Demarcacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Goiztiri/Goiztiri/Views/Jugadores/Femenino.cshtml
@model IEnumerable<GoiztiriWeb.Models.Jugador>

@{
    ViewBag.Title = "Femenino";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="align-items-center" style="margin-top:10px" >
<h2 class="display-4">Femenino</h2>
 </div>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ruta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dorsal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Goles)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Asistencias)
            </th>
            <th>
                Demarcación
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (item.CodEquipo == 1)
            {
            <tr>
                <td>
                    <img class="rounded" height="80" width="80" src="@Url.Content(item.Ruta)" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dorsal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Goles)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Asistencias)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Demarcacion)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.CodJugador }) |
                    @Html.ActionLink("Details", "Details", new { id = item.CodJugador }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CodJugador })
                </td>
            </tr>
                }
            }

    </table>
</div>

Goiztiri/Goiztiri/Views/Jugadores/Index.cshtml
@model IEnumerable<GoiztiriWeb.Models.Jugador>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <h2 class="h2">Jugadores</h2>


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ruta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dorsal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Goles)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Asistencias)
            </th>
            <th>
               Demarcación
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img class="rounded" height="80" width="80" src="@Url.Content(item.Ruta)" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dorsal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Goles)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Asistencias)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Demarcacion)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.CodJugador }) |
                    @Html.ActionLink("Details", "Details", new { id = item.CodJugador }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CodJugador })
                </td>
            </tr>
        }

    </table>
</div>

Goiztiri/Goiztiri/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

   @* <div class="fixed-top">*@
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary" >
        <div>
            <img class="navbar-brand" src="~/Content/img/iconos/escudo.png" width="100" height="100" />
        </div>
        @Html.ActionLink("Goiztiri", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-header" id="navbarColor01">
            <ul class="navbar-nav mr-auto nav-tabs">
                <li class=" active ">
                    @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-item nav-link" })
                </li>
                <li class="dropdown nav-item nav-link ">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Plantillas</a>
                    <div class="dropdown-menu">

                        @Html.ActionLink("Femenino", "Femenino", "Jugadores", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Senior A", "Index", "Jugadores", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Senior B", "Index", "Jugadores", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Juvenil", "Index", "Jugadores", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Cadete", "Index", "Jugadores", new { area = "" }, new { @class = "dropdown-item" })

                    </div>
                </li>
                <li>
                    @Html.ActionLink("Clasificación", "Index", "Home", new { area = "" }, new { @class = "nav-item nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contacto", "Index", "Home", new { area = "" }, new { @class = "nav-item nav-link" })
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    @*</div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>